const pois = [{ort: 'Hyderabad',
foto: 'paigah.jpg',
alt: 'paigah',
link: 'https://www.tripadvisor.de/Attraction_Review-g297586-d3705691-Reviews-Paigah_Tombs-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Paigah Tombs',
text: 'Paigah Gräber oder Maqhbara Shams al - Umara sind eines der berühmtesten Denkmäler der Stadt Hyderabad. Sie sind bekannt für ihre ausgezeichnete architektonische Schönheit.'},
{ort: 'Hyderabad',
foto: 'marychurch.jpg',
alt: 'marychurch',
link: 'http://www.telanganatourism.gov.in/partials/destinations/divine-destinations/hyderabad/st-marys-church.html',
place: 'St. Marys Church',
text: 'Die St. Mary\'s Church in Secunderabad ist die älteste römisch-katholische Kirche in der Stadt. Diese faszinierende Kirche wurde im Indo-gotischen Stil erbaut und 1850 geweiht. Die St. Mary\'s Church, die der verehrten Jungfrau Maria geweiht ist, ist ein großartiges Wahrzeichen der Stadt. Sie ist für ihre architektonische Exzellenz und unglaubliche Geschichte gelobt.'},
{ort: 'Hyderabad',
foto: 'qutab.jpg',
alt: 'qutab',
link: 'https://www.tripadvisor.de/Attraction_Review-g297586-d3705854-Reviews-Qutab_Shahi_Tombs-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Qutb Shahi Tombs',
text: 'Die ursprünglich stark verwahrlosten Gräber der Qutab-Shah-Könige wurden später von einem Minister der Nizams (Salar Jang I.) in mühevoller Arbeit restauriert. Heute sind alle Qutab-Shah-Könige in der etwa 1,5km nördlich der Golconda-Festung gelegenen Anlage begraben (außer Abdul Hassan Tana Shah), sowie einige andere Mitglieder der Königsfamilie.'},
{ort: 'Hyderabad',
foto: 'golconda.jpg',
alt: 'golconda',
link: 'https://www.tripadvisor.de/AttractionProductDetail-g297586-d12470262-Golconda_Fort_Sound_and_Light_Show_from_Hyderabad_with_Private_Transport-Hyderabad_Hyderabad_District_Telangana.html?from_tpa=true',
place: 'Golconda Fort',
text: 'Das schon im 13. Jahrhundert - jedoch nicht in seiner heutigen Form - erwähnte Fort ist eine der größten Festungen, die Indien zu bieten hat. Die meisten der heute noch zu bewundernden Anlagenbereiche stammen jedoch aus dem 16.-17. Jahrhundert, also aus der Zeit des Qutab-Shah Imperiums. Golconda ist nicht nur von einem Graben, sondern von einem Ring aus drei Mauern umgeben. Dabei gibt es auf einer Länge von etwa 11 km rund um das Fort acht Tore und knapp über 85 Bastionen. Das höchste Gebäude der Festung stellt die Zitadelle (Balahisar) mit etwa 110 Metern Höhe dar. Eine Sound- & -Light Show findet jeweils am Mittwoch und am Sonntag statt.'},
{ort: 'Hyderabad',
foto: 'charminar.jpg',
alt: 'charminar',
link: 'https://www.tripadvisor.de/Attraction_Review-g297586-d320668-Reviews-Charminar-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Charminar',
text: '1591 von Mohamed Quali Qutab Shah erbaut, steht der riesige Torbogen (53m hoch) inmitten der Altstadt Abids. Errichtet wurde der 4-türmige Bau nach Beendigung einer großen Seuche, wie es heißt. Er steht auf einem fast quadratischen Fundament und die Höhe der 4 Bögen reicht bereits 15 Meter. Im Inneren befindet sich eine Moschee. Oberhalb der Torbögen ziehen sich herrliche Arkadengänge um den gesamten Bau. Der Char Minar ist allabendlich ab 19 Uhr für 2 Stunden beleuchtet, was insbesondere für die Fotografen unter den Reisenden ein schönes Motiv bietet.'},
{ort: 'Hyderabad',
foto: 'mecca.jpg',
alt: 'mecca',
link: 'https://www.tripadvisor.de/Attraction_Review-g297586-d3705173-Reviews-Mecca_Masjid-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Mecca Masjid',
text: 'Die wohl größte Moschee Indiens steht direkt gegenüber des Char Minar. Die unter Mohamed Quli Qutab Shah 1614 iniziierte Moschee soll bis zu 10.000 Menschen fassen können. Sie wurde schließlich zu Herrschaftszeiten von Aurangzeb im Jahre 1687 fertiggestellt, der jedoch die ursprünglichen Pläne aus Geldmangel verändern musste, was insbesondere die Minarette nicht so groß wie geplant ausfallen ließ. Die gesamte Erscheinung wurde der Moschee in Mecca versucht nachzuempfinden. Riesige Granitblöcke wurden dazu herangeschafft. Die Gräber der Nizam Herrscher (ab 1803) befinden sich links neben der Moschee.'},
{ort: 'Hyderabad',
foto: 'chowmahalla.jpg',
alt: 'chowmahalla',
link: 'https://www.tripadvisor.de/Attraction_Review-g297586-d1020670-Reviews-Chowmahalla_Palace-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Chowmahalla Palace',
text: 'Chowmahalla Palace oder Chowmahallatuu, ist ein Palast der Nizams des Staates Hyderabad. Es war der Sitz der Asaf Jahi Dynastie und war die offizielle Residenz der Nizams von Hyderabad, während sie ihren Staat regierten.'},
{ort: 'Hyderabad',
foto: 'salarjung.jpg',
alt: 'salarjung',
link: 'https://www.tripadvisor.de/Attraction_Review-g297586-d320681-Reviews-Salar_Jung_Museum-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Salarjung Museum',
text: 'Das Museum zeigt großflächig den Sammeleifer des Premierministers der Nizams namens Mir Yusuf Ali Khan. Die über 30.000 Ausstellungsstücke aus aller Welt umfassen Manuskripte, Gemälde, Figuren, Waffen, Zeichnungen, Schmuck, Bücher und einige Stücke von besonderem historischen Wert. Die Öffnungszeiten sind von 10-17 Uhr (außer Freitags).'},
{ort: 'Hyderabad',
foto: 'lumbini.jpg',
alt: 'lumbini',
link: 'https://www.tripadvisor.de/Attraction_Review-g297586-d1228084-Reviews-Lumbini_Park-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Lumbini Park',
text: 'Lumbini Park ist ein kleiner öffentlicher, städtischer Park von 7,5 Hektar neben Hussain Sagar in Hyderabad, Indien. Indien, benannt nach Lumbini aus Nepal, ist Lord Buddha gewidmet.'},
{ort: 'Hyderabad',
foto: 'birla.jpg',
alt: 'birla',
link: 'https://www.tripadvisor.de/Attraction_Review-g297586-d1021934-Reviews-Birla_Mandir-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Birla Mandir',
text: 'Dieser relativ neue hinduistische Tempel (in den 70er Jahren erbaut) ist dem Gott Venkateswara gewidmet. Er liegt hoch auf dem Hügel am südlichen Ende des Hussain Sagar Sees. Besonders schön ist er, weil sein weißer Marmor, der übrigens aus Rajastan kommen soll, noch bis weit zu sehen sein soll. Besonders empfehlenswert ist dieser Ort, um abends den Sonnenuntergang über Hyderabad zu beobachten. (Öffnungszeiten sind von 7-12 und von 15-21 Uhr)'},
{ort: 'Hyderabad',
foto: 'moulaali.jpg',
alt: 'moulaali',
link: 'https://www.tripadvisor.de/Attraction_Review-g297586-d3913330-Reviews-Moula_Ali_Dargaha-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Moula Ali',
text: 'Moula Ali-Hügel ist ein monadnock oder kuppelförmiger Hügel, der in Moula Ali, Hyderabad, Indien gelegen ist. Es ist bekannt für die Moula Ali Dargah und einen heiligen Stein, die beide oben auf dem Hügel sind.'},
{ort: 'Hyderabad',
foto: 'ramoji.jpg',
alt: 'ramoji',
link: 'https://www.tripadvisor.de/Attraction_Review-g297586-d636879-Reviews-Ramoji_Film_City-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Ramoji Film City',
text: 'Ramoji Film City (RFC) ist der weltgrößte Filmstudio-Komplex und liegt in Indien. Er öffnete 1996, umfasst insgesamt fünf Quadratkilometer und liegt etwa 25 Kilometer von Hyderabad entfernt. Eigentümer ist der Geschäftsmann Ramoji Rao mit seiner Ramoji Group.'},
{ort: 'Hyderabad',
foto: 'falaknuma.jpg',
alt: 'falaknuma',
link: 'https://www.tripadvisor.de/Attraction_Review-g297586-d320672-Reviews-Taj_Falaknuma_Palace-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Falaknuma Palace',
text: 'Auf einer Höhe von gut 600 m über der Stadt Hyderabad liegt diese luxuriöse 5-Sterne-Unterkunft mit einer Mischung aus kolonialen und indischen Designs. Das Taj Falaknuma Palace liegt nur 5 km von dem schönen Denkmal Charminar und dem Chaumallah Palace entfernt.'},
{ort: 'Hyderabad',
foto: 'taramati.jpg',
alt: 'taramati',
link: 'https://www.tripadvisor.de/Restaurant_Review-g297586-d7960120-Reviews-Taramati_Baradari-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Taramati Baradari',
text: 'Taramati Baradari ist ein historischer Sarai als Teil von Ibrahim Bagh, einem persischen Garten, der während der Herrschaft von Ibrahim Quli Qutub Shah, dem vierten Sultan von Golconda, erbaut wurde.'},
{ort: 'Hyderabad',
foto: 'durgam.jpg',
alt: 'durgam',
link: 'https://www.tripadvisor.de/Attraction_Review-g297586-d3187577-Reviews-Durgam_Cheruvu_Lake-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Durgam Cheruvu',
text: 'Durgam Cheruvu auch bekannt als Raidurgam Cheruvu ist ein Süßwassersee in Rangareddy Bezirk, Telangana, Indien. Der See, der sich über 83 Hektar erstreckt, liegt in der Nähe der Stadt Hyderabad.'},
{ort: 'Hyderabad',
foto: 'miniature.jpg',
alt: 'miniature',
link: 'https://www.tripadvisor.de/Hotel_Review-g297586-d1150070-Reviews-Dhola_ri_Dhani-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Dhola-Ri-Dhani Miniature Rajasthani Village',
text: 'Dhola-Ri-Dhani Miniature Rajasthani Village ist eine Miniaturwelt im Norden von Hyderabad. Es stellt ein typisch Rajasthanisches Dorf dar.'},
{ort: 'Hyderabad',
foto: 'jagannath.jpg',
alt: 'jagannath',
link: 'https://www.tripadvisor.de/Attraction_Review-g297586-d3598152-Reviews-Shri_Jagannath_Temple-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Shri Jagannath Temple',
text: 'Der Jagannath-Tempel in Hyderabad, Indien ist ein moderner Tempel, der von der Odia-Gemeinschaft der Stadt von Hyderabad errichtet wurde, die dem hinduistischen Gott Jagannath eingeweiht wird.'},
{ort: 'Hyderabad',
foto: 'nizam.jpg',
alt: 'nizam',
link: 'https://www.tripadvisor.de/Attraction_Review-g297586-d2542488-Reviews-Purani_Haveli-Hyderabad_Hyderabad_District_Telangana.html',
place: 'Nizam Museum / Purani Haveli',
text: 'Purani Haveli ist ein herausragendes Beispiel für das Verschmelzen diverser Architekturstile in Indien. Die Palastanlage wurde ursprünglich im 16. Jahrhundert erbaut und dann 200 Jahre später restauriert und mit europäischen Elementen versehen. Der hufeisenförmige Komplex umfasst einen Palast, ein (Nizam) Museum und eine Schule. Zudem befinden sich hier der „längste Kleiderschrank der Welt“, Oldtimer und kostbare Antiquitäten.'},
{ort: 'Hyderabad',
foto: 'madventure.jpg',
alt: 'madventure',
link: 'https://highwayonlyway.com/2014/04/09/high-on-hyderabad-madventure-quad-biking-fun-off-the-road/',
place: 'Madventure - Mit Quad entlang der Mangobäume',
text: 'Madventure ist eigentlich eine Mango-Plantage, die in eine Abenteuersportarena umgewandelt wurde, die Umgebung ist ruhig und angenehm. Das Fahren auf den Einsitzer-Bikes ist der wahre Spaß, das Manövrieren des Fahrzeugs erfordert etwas Geschick, da die Strecke an manchen Stellen etwas hart wird! Für diejenigen, die nicht fahren können oder mit den Bikes umgehen, können Doppelsitzer nehmen zusammen mit einem anderen Fahrer. Eine Fahrt auf diesem Weg führt Sie weiter in den Obstgarten mit Mangobäumen auf beiden Seiten.'},
{ort: 'Nalgonda',
foto: 'gandhitemple.jpg',
alt: 'gandhitemple',
link: 'http://www.telanganatourism.gov.in/partials/destinations/divine-destinations/nalgonda/mahatma-gandhi.html',
place: 'Mahatma Gandhi Temple',
text: 'Das Pedda Kaparthy Dorf in der Nähe von Chityal, Nalgonda in Telangana, ist die Heimat eines Mahatma Gandhi Tempels, der der erste dieser Art ist und von überall her Aufmerksamkeit auf sich zieht. Der Vater der Nation wird hier als Gott verehrt, während Geweihte hierher kommen, um Segen zu erbitten und Gebete zu sprechen.'},
{ort: 'Nalgonda',
foto: 'devarakonda.jpg',
alt: 'devarakonda',
link: 'http://www.telanganatourism.gov.in/partials/destinations/heritage-spots/nalgonda/devarakonda-fort.html',
place: 'Devarakonda Fort',
text: 'Devarakonda ist ein kleines Dorf im Distrikt Nalgonda. Das Dorf Devarakonda beherbergt eine der erstaunlichsten Forts in Telangana. Es gab eine Zeit, in der das Fort hoch stand, um den Ruhm des Dorfes zu zeigen, aber jetzt, aufgrund der Nachlässigkeit, ist das Fort in Trümmern.'},
{ort: 'Nalgonda',
foto: 'kolanupaka.jpg',
alt: 'kolanupaka',
link: 'http://www.telanganatourism.gov.in/partials/destinations/heritage-spots/nalgonda/kolanupaka.html',
place: 'Kolanupaka',
text: 'Kolanupaka ist ein beliebtes Dorf in Alair Mandal im Distrikt Nalgonda. Dieses Dorf ist die Heimat eines bemerkenswerten Jain-Tempels. Der Tempel ist bekannt für seine unglaubliche Architektur und ist seit über zweitausend Jahren ein Geschenk. Sobald Sie den Tempel betreten, umgibt Sie eine Aura der Reinheit. Im Inneren des Tempels gibt es einige wundervolle Bilder von den Jains, den großen Meistern des endgültigen Wissens.'},
{ort: 'Nalgonda',
foto: 'nagarjuna.jpg',
alt: 'nagarjuna',
link: 'http://www.telanganatourism.gov.in/partials/destinations/heritage-spots/nalgonda/nagarjuna-sagar.html',
place: 'Nagarjuna Sagar',
text: 'Der Nagarjuna Sagar-Staudamm, der während der Hochwassersaison in Monsun seine Tore öffnet, gilt als einer der größten Staudämme, die in jüngster Zeit in Asien gebaut wurden. Als der höchste Staudamm ist Nagarjuna Sagar Dam auch der Stolz von Indien. Der kolossale Damm wurde zum Zwecke der Wasserversorgung und Bewässerung in den Bezirken Telangana und Nalgonda / Khammam errichtet.'},
{ort: 'Nalgonda',
foto: 'nandikonda.jpg',
alt: 'nandikonda',
link: 'http://www.telanganatourism.gov.in/partials/destinations/heritage-spots/nalgonda/nandikonda.html',
place: 'Nandikonda',
text: 'Nandikonda ist ein kleines Dorf am Ufer des Flusses Krishna im Stadtteil Nalgonda. Es liegt in der Nähe des prächtigen Nagarjuna Sagar Staudamms. Nandikonda war Teil der Ikshvaku-Dynastie und das Dorf wurde berühmt, nachdem Dutzende von alten buddhistischen Strukturen wie Säulenhallen und Klöster ausgegraben wurden.'},
{ort: 'Nalgonda',
foto: 'rachakonda.jpg',
alt: 'rachakonda',
link: 'http://www.telanganatourism.gov.in/partials/destinations/heritage-spots/nalgonda/rachakonda-fort.html',
place: 'Rachakonda Fort',
text: 'Das Fort steht als glorreiche Demonstration der Vemula-Herrscher und ihrer Macht. Das Fort ist derzeit in Ruinen. Dieser Inbegriff der mittelalterlichen hinduistischen Kunst und Kultur zieht jedoch immer noch zahlreiche Menschen an. Ein weiteres hervorstechendes Merkmal dieses Tempels ist, dass er perfekt den Prinzipien von Vasthu Shastra folgt, die die meisten Hindu-Architekturen beeinflusst.'},
{ort: 'Nalgonda',
foto: 'bhongir.jpg',
alt: 'bhongir',
link: 'http://www.telanganatourism.gov.in/partials/destinations/heritage-spots/nalgonda/bhongir-fort.html',
place: 'Bhongir Fort',
text: 'Die Bhongir-Festung ist eine massive, uneinnehmbare Struktur, die von Chalukya-Herrscher Tribhuvanamalla Vikramaditya VI errichtet wurde. Die Festung ist nach ihm benannt. Die Geschichte der Festung von Bhongir wurde bis ins 10. Jahrhundert zurückverfolgt. Anfangs hieß es Tribhuvanagiri, später wurde es in Bhuvanagiri umbenannt und schließlich wurde es Bhongir Fort.'},
{ort: 'Warangal',
foto: 'thousandpillars.jpg',
alt: 'thousandpillars',
link: 'https://www.tripadvisor.de/Attraction_Review-g735768-d3161445-Reviews-Thousand_Pillar_Temple-Warangal_Warangal_Urban_District_Telangana.html',
place: 'Thousand Pillars Temple',
text: 'Der Thousand-Säulen-Tempel, der sich in Hanamkonda befindet, ist einer der wichtigsten Teile der Warangal City. Der Tempel wurde 1163 von dem großen Rudra Deva erbaut. Jeder Teil des Tempels zeigt den typischen Chalukya-Baustil. Der Thousand Pillar Tempel hat drei präsidierende Gottheiten, Lord Vishnu, Shiva und Surya Deva. Der Tempel steht als Statement der feinsten Künste der Kakatiyas.'},
{ort: 'Warangal',
foto: 'ramappa.jpg',
alt: 'ramappa',
link: 'https://www.tripadvisor.de/Attraction_Review-g735768-d3705184-Reviews-Ramappa_Temple-Warangal_Warangal_Urban_District_Telangana.html',
place: 'Ramappa Temple',
text: 'Der mittelalterliche Deccan Ramappa-Tempel aus dem Jahr 1213 wurde unter der Schirmherrschaft des Kakatiya-Herrschers Kakati Ganapathi Deva unter der Leitung seines Oberbefehlshabers Rudra Samani am Ort Ranakude in der Atukuru-Provinz errichtet. Der Ramappa Tempel ist das richtige Ziel für Menschen, die architektonische Brillanz bewundern und einen Panoramablick auf wahre landschaftliche Schönheit haben.'},
{ort: 'Warangal',
foto: 'warangalfort.jpg',
alt: 'warangalfort',
link: 'https://www.tripadvisor.de/Attraction_Review-g735768-d2668325-Reviews-Warangal_Fort-Warangal_Warangal_Urban_District_Telangana.html',
place: 'Warangal Fort',
text: 'Das Warangal Fort, die Hauptattraktion der Stadt Warangal, erstreckt sich über einen Radius von 19 Kilometern zwischen Warangal und Hanamkonda. Das Fort wurde im 13. Jahrhundert unter der Herrschaft des Kakateya-Königs Ganapati Deva erbaut. Das Warangal Fort ist berühmt für seine anmutigen und endlich geschnitzten Bögen und Säulen. Diese Festung hat vier große Steintore.'},
{ort: 'Warangal',
foto: 'bogatha.jpg',
alt: 'bogatha',
link: 'http://www.telanganatourism.gov.in/partials/destinations/nature-discovery/khammam/bogatha-waterfall.html',
place: 'Bogatha Waterfall',
text: 'Der Bogatha-Wasserfall bietet ein herrliches Schauspiel von fallendem Wasser und einer reichen Landschaft und wird daher treffend als Niagara von Telangana bezeichnet. Da eine befahrbare Straße nicht zur Verfügung steht, müssen die Besucher einige Strecken zurücklegen.'},
{ort: 'Warangal',
foto: 'pakhallake.jpg',
alt: 'pakhallake',
link: 'https://www.tripadvisor.de/Attraction_Review-g735768-d3705300-Reviews-Pakhal_Lake-Warangal_Warangal_Urban_District_Telangana.html',
place: 'Pakhal Lake - Wildtier- und Safaripark',
text: 'This is one of the most popular picnic spots in Warangal. Pakhal Lake, gives you a calming and soothing trip amidst undulating forest hills and dales. The lake was constructed in the 1213 AD by the Kakatiya king Ganapathi Dev.'},
{ort: 'Warangal',
foto: 'laknavaram.jpg',
alt: 'laknavaram',
link: 'https://www.tripadvisor.de/Attraction_Review-g735768-d9811257-Reviews-Laknavaram_Cheruvu-Warangal_Warangal_Urban_District_Telangana.html',
place: 'Laknavaram Lake',
text: 'Der Lakhnavaram See, in Govindaraopet Mandal etwa 70 Kilometer von Warangal entfernt, ist ein beliebter Picknickplatz. Der See ist eine außergewöhnliche Schönheit. Der See wurde durch die Schließung von drei engen Tälern gebildet. Jedes Tal wird durch einen kurzen Wall ersetzt und Hügel dienen als natürliche Barriere. Der See wurde von den Herrschern der Kakatiya-Dynastie im 13. Jahrhundert erbaut.'},
{ort: 'Jaipur',
foto: 'amberfort.jpg',
alt: 'amberfort',
link: 'https://www.tripadvisor.de/Attraction_Review-g1096234-d319875-Reviews-Amber_Fort-Amer_Jaipur_Jaipur_District_Rajasthan.html',
place: 'Amber Fort / Amber Palast',
text: 'Die Fahrt von Jaipur nach Amber führt über kurvenreiche Straßen durch die Bergketten des Aravalli-Gebirges. Unerwartet taucht nach einer scharfen Biegung die mächtige Festungsanlage von Fort Amber auf dem Kamm eines Berghanges auf. Verstärkt wird der eindrucksvolle Anblick der wehrhaften Anlage durch die Spiegelungen im darunter liegenden See.'},
{ort: 'Jaipur',
foto: 'nahargarh.jpg',
alt: 'nahargarh',
link: 'https://www.tripadvisor.de/Attraction_Review-g304555-d311641-Reviews-Nahargarh_Fort-Jaipur_Jaipur_District_Rajasthan.html',
place: 'Nahargarh Fort',
text: 'Nahargarh Fort steht am Rande der Aravalli Hills, mit Blick auf die Stadt Jaipur im indischen Bundesstaat Rajasthan. Zusammen mit Amer Fort und Jaigarh Fort bildete Nahargarh einst einen starken Verteidigungsring für die Stadt.'},
{ort: 'Jaipur',
foto: 'jaigarh.jpg',
alt: 'jaigarh',
link: 'https://www.tripadvisor.de/Attraction_Review-g304555-d325116-Reviews-Jaigarh_Fort-Jaipur_Jaipur_District_Rajasthan.html',
place: 'Jaigarh Fort',
text: 'Auf den Hügeln hoch über Amber thront das stattliche Jaigarh-Fort aus dem 17.Jh. Seine wuchtigen Mauern Ziehen sich scheinbar kilometerrweit über die Hänge.Über den Wällen ragt der Diva Burj, ein gewaltiger Wachttum, empor. Einst zählte er sieben Geschosse- einer Legende nach soll ihm jedoch der Blitz , der ihm die in solcher Höhe brennende Lampe mißgönnte, die oberen beiden Stockwerke abgeschlagen haben.'},
{ort: 'Jaipur',
foto: 'surya.jpg',
alt: 'surya',
link: 'https://www.tripadvisor.de/Attraction_Review-g304555-d1641277-Reviews-Surya_Mandir-Jaipur_Jaipur_District_Rajasthan.html',
place: 'Sun Temple (Surya Mandir)',
text: 'Surya Mandir Jaipur ist ein kleiner Satellitentempel Teil des größeren Galta Ji Tempelkomplexes, der westlich von Jaipur liegt. Von dem großen Aussichtspunkt des Tempels, 200 Meter über der Stadt, gibt es wunderbare Panoramablicke, die man am besten bei Sonnenuntergang betrachten kann.'},
{ort: 'Jaipur',
foto: 'monkey.jpg',
alt: 'monkey',
link: 'https://www.tripadvisor.de/Attraction_Review-g304555-d311634-Reviews-Monkey_Temple_Galta_Ji-Jaipur_Jaipur_District_Rajasthan.html',
place: 'Monkey Temple (Hanuman Temple)',
text: 'Erbaut in einem Bergpass in den Aravalli Hills, 10 km östlich von Jaipur, ist Galtaji seit dem frühen 15. Jahrhundert ein Zufluchtsort für hinduistische Asketen der vaishnav Ramanuj Sekte. Der Haupttempel ist der Tempel von Galtaji, in rosa Stein gebaut. Der Tempel verfügt über eine Reihe von Pavillons mit abgerundeten Dächern, geschnitzten Säulen und bemalten Wänden. Der Komplex ist um eine natürliche Quelle und Wasserfälle angelegt, die 7 Pools bilden, der obere und der untere Pool werden von Pilgern zum Baden genutzt.'},
{ort: 'Jaipur',
foto: 'hawa.jpg',
alt: 'hawa',
link: 'https://www.tripadvisor.de/Attraction_Review-g304555-d317345-Reviews-Hawa_Mahal_Palace_of_Wind-Jaipur_Jaipur_District_Rajasthan.html',
place: 'Hawa Mahal',
text: 'Hawa Mahal lautet die indische Bezeichnung für den Palast der Winde. Das fünfstöckige Gebäude befindet sich in der Altstadt von Jaipur. Die drei Millionen Einwohner zählende Metropole ist die Hauptstadt des indischen Bundesstaates Rajasthan. Der Palast der Winde liegt an einer viel befahrenen Straße im Herzen der Stadt.'},
{ort: 'Jaipur',
foto: 'jalmahal.jpg',
alt: 'jaimahal',
link: 'https://www.tripadvisor.de/Attraction_Review-g304555-d324664-Reviews-Jal_Mahal-Jaipur_Jaipur_District_Rajasthan.html',
place: 'Water Palace (Jai Mahal)',
text: 'Jal Mahal (bedeutet "Wasserpalast") ist ein Palast in der Mitte des Man Sagar Sees in der Stadt Jaipur, der Hauptstadt des Bundesstaates Rajasthan, Indien. Der Palast und der See um ihn herum wurden im 18. Jahrhundert von Maharaja Jai Singh II von Amber renoviert und erweitert.'},
{ort: 'Jaipur',
foto: 'citypalace.jpg',
alt: 'citypalace',
link: 'https://www.tripadvisor.de/Attraction_Review-g304555-d324468-Reviews-City_Palace_of_Jaipur-Jaipur_Jaipur_District_Rajasthan.html',
place: 'City Palace',
text: 'Der Stadtpalast mit den Palästen Chandra Mahal und Mubarak Mahal und anderen Gebäuden war der Sitz des Maharaja von Jaipur, dem Oberhaupt des Kachwaha Rajput Clans. Der Chandra Mahal Palast beherbergt heute ein Museum, aber der größte Teil davon ist immer noch eine königliche Residenz. Der Palastkomplex, der sich nordöstlich des Zentrums der rasterförmigen Stadt Jaipur befindet, umfasst eine beeindruckende und große Anzahl von Innenhöfen, Gärten und Gebäuden.'},
{ort: 'Jaipur',
foto: 'jantarmantar.jpg',
alt: 'jantarmantar',
link: 'https://www.tripadvisor.de/Attraction_Review-g304555-d311635-Reviews-Jantar_Mantar_Jaipur-Jaipur_Jaipur_District_Rajasthan.html',
place: 'Jantar Mantar',
text: 'Das Jantar Mantar Denkmal in Jaipur, Rajasthan ist eine Sammlung von neunzehn architektonischen astronomischen Instrumenten, die vom Rajput König Sawai Jai Singh II gebaut und 1734 vollendet wurden.'},
{ort: 'Agra',
foto: 'taj.jpg',
alt: 'taj',
link: 'https://www.tripadvisor.de/Attraction_Review-g297683-d317329-Reviews-Taj_Mahal-Agra_Agra_District_Uttar_Pradesh.html',
place: 'Taj Mahal',
text: 'Der Bau des wohl bekanntesten Bauwerkes für ganz Indien wurde von Shah Jahan im Jahre 1631 begonnen. Fertiggestellt werden konnte der Hauptkomplex mit Hilfe von wie es heißt über 20.000 Arbeitern, Architekten und anderen Experten jedoch erst im Jahr 1653. Die Öffnungszeiten sind von 8-17 Uhr. Wer vor 8 oder nach 17 Uhr hinein möchte, muss einen erheblich höheren Eintrittspreis bezahlen (etwa 100 Rs). Es ist besonders ratsam, sich das Taj Mahal zu verschiedenen Tageszeiten anzusehen, da sich je nach Sonnenrichtung die Farben und damit die gesamte Aura des Taj Mahal ändert.'},
{ort: 'Agra',
foto: 'agrafort.jpg',
alt: 'agrafort',
link: 'https://www.tripadvisor.de/Attraction_Review-g297683-d319695-Reviews-Agra_Fort-Agra_Agra_District_Uttar_Pradesh.html',
place: 'Fort Agra',
text: 'Es ist das Fort, in dem Shah Jahan von seinem Sohn Aurangzeb bis zu seinem Tode gefangen gehalten wurde. Das Fort wird umgeben von einem 2,5 km langen und einer etwa 19 Meter hohen Mauer, sowie einem recht breiten Graben. Im Inneren befinden sich viele sehr eindrucksvolle Gebäude, darunter die Perlenmoschee (Moti Masjid), die Audienzhalle (Diwan-i-Am) und der Palast von Jehangir. Die Öffnungszeiten sind von 8-18 Uhr.'},
{ort: 'Agra',
foto: 'fatehpur.jpg',
alt: 'fatehpur',
link: 'https://www.tripadvisor.de/Attraction_Review-g797802-d324659-Reviews-Buland_Darwaza-Fatehpur_Sikri_Agra_District_Uttar_Pradesh.html',
place: 'Fatehpur Sikri (Panch Mahal, Tor Buland Darwaza)',
text: 'Mogulstadt mit einem Stadtbild, das in der heutigen Form bereits vor 500 Jahren existierte. Das vollständig erhaltene Gebäudeensemble veranlasste die UNESCO, die gesamte Innenstadt von Fatehpur Sikri zum Weltkulturerbe der Menschheit zu erklären. Heute zählt die nordindische Stadt rund 30.000 Einwohner.'},
{ort: 'Delhi',
foto: 'chandni.jpg',
alt: 'chandni',
link: 'https://www.tripadvisor.de/Attraction_Review-g304551-d311613-Reviews-Chandni_Chowk-New_Delhi_National_Capital_Territory_of_Delhi.html',
place: 'Chandni Chowk',
text: 'Das Geschäftsgebiet Chandni Chowk (auch Silver Square) im Stadtteil Mughal wurde mit großem Einsatz von Jahanara Begum entworfen. Der farbenfrohe und lebendige Markt liegt an der Hauptstraße von Alt-Delhi, an seinem östlichen Ende befindet sich das Rote Fort.'},
{ort: 'Delhi',
foto: 'indiagate.jpg',
alt: 'indiagate',
link: 'https://www.tripadvisor.de/Attraction_Review-g304551-d321493-Reviews-India_Gate-New_Delhi_National_Capital_Territory_of_Delhi.html',
place: 'India Gate',
text: 'Das von Lutyens erbaute Tor von Indien (India Gate) liegt am Fuße der Straße des Rashtrapati Bhavan. Das Tor ist ein 42 Meter hoher Bogen, in den etwa 85.000 Namen von Soldaten eingraviert sind, in Erinnerung an die Kriege mit Afghanistan und die beiden Weltkriege. In dem Tor von Indien brennt ein stetiges Feuer (Amar Jawan Jyoti) in Gedenken an die Opfer. Unter dem Bogen befindet sich ein Denkmal für den Unbekannten Soldaten (unknown soldier).'},
{ort: 'Delhi',
foto: 'rotesfort.jpg',
alt: 'rotesfort',
link: 'https://www.tripadvisor.de/Attraction_Review-g304551-d319701-Reviews-Red_Fort_Lal_Quila-New_Delhi_National_Capital_Territory_of_Delhi.html',
place: 'Lal Quila (Rotes Fort)',
text: 'Das Rote Fort (Red Fort) oder auch Lal Qila, ist das Wahrzeichen für Macht und Kontrolle. Nachdem der Grundstein bereits 1618 gelegt wurde, erbaute der Großmogul Shah Jahan das aus rotem Sandstein bestehende Fort schließlich in den Jahren von 1638-48. Seitdem ist dieses mächtige Bauwerk Schauplatz für viele politische Ereignisse gewesen, so z.B. die Rede des ersten indischen Premierministers Pandit Jawharlal Nehru, der hier die Unabhängigkeit von Großbritannien erklärte.'},
{ort: 'Delhi',
foto: 'gandhi.jpg',
alt: 'gandhi',
link: 'https://www.tripadvisor.de/Attraction_Review-g304551-d1976642-Reviews-Raj_Ghat-New_Delhi_National_Capital_Territory_of_Delhi.html',
place: 'Mahatma Gandhi Denkmal',
text: 'Das Mahatma Gandhi Denkmal liegt auf der Sadar Patel Marg. Gandhi, der gewaltfreien Widerstand leistete und damit zur bekanntesten Person Indiens wurde, starb 1948, als er von einen Hindu ermordet wurde. Der Besuch des Gandhi Denkmals lohnt sich sehr.'},
{ort: 'Delhi',
foto: 'purana.jpg',
alt: 'purana',
link: 'https://www.tripadvisor.de/Attraction_Review-g304551-d324111-Reviews-Purana_Qila-New_Delhi_National_Capital_Territory_of_Delhi.html',
place: 'Purana Quila',
text: 'Dieser Ort wird als das ursprüngliche Indraprasthra, also die Hauptstadt Pandavas vermutet. Viele der Bauwerke stammen aus der Zeit von Sher Shah Suri.'},
{ort: 'Delhi',
foto: 'tughlaqabad.jpg',
alt: 'tughlaqabad',
link: 'https://www.tripadvisor.de/Attraction_Review-g304551-d2318709-Reviews-Tughluqabad_Fort-New_Delhi_National_Capital_Territory_of_Delhi.html',
place: 'Tughlaqabad Fort',
text: 'Als dritter Stadtteil Delhis mit 13 Zuwegen wurde Tughlaqabad von Ghiyas-ud-din Tughlaq gebaut.'},
{ort: 'Delhi',
foto: 'jamamasjid.jpg',
alt: 'jamamasjid',
link: 'https://www.tripadvisor.de/Attraction_Review-g304551-d311619-Reviews-Friday_Mosque_Jama_Masjid-New_Delhi_National_Capital_Territory_of_Delhi.html',
place: 'Jama Masjid',
text: 'Die Yami Masjid Moschee ist die größte und wahrscheinlich auch schönste Moschee Indiens. Mit weißem und schwarzen Marmor sowie rotem Sandstein wurde sie von Shah Jahan erbaut. Heute ist sie Gebetsstätte für viele Tausend Moslems. Sie liegt gegenüber des Roten Forts und ist umgeben von dem großen Chatta Chowk Markt.'},
{ort: 'Delhi',
foto: 'qutubminar.jpg',
alt: 'qutubminar',
link: 'https://www.tripadvisor.de/Attraction_Review-g304551-d311626-Reviews-Qutub_Minar-New_Delhi_National_Capital_Territory_of_Delhi.html',
place: 'Qutub Minar',
text: 'Der Grundstein des Qutab Minar wurde im Jahr 1199 durch Qutb-u-d-Din Aibak mit einem ersten Stockwerk gelegt. Mit seinem roten Sandstein ist er der höchste Turm Indiens und diente zum Predigen, denn aus der Höhe wurde ein Prediger besser gehört. Bis 1236 wurden durch Shamsu-d-Din IItutmish insgesamt drei weitere Stockwerke errichtet. Alle Stockwerke sind von kleinen Balkonen umrundet.'},
{ort: 'Delhi',
foto: 'humayun.jpg',
alt: 'humayun',
link: 'https://www.tripadvisor.de/Attraction_Review-g304551-d311618-Reviews-Humayun_s_Tomb-New_Delhi_National_Capital_Territory_of_Delhi.html',
place: 'Humayun-Mausoleum',
text: 'Das Humayun-Mausoleum, das zu den bedeutendsten Bauwerken der Mogul-Epoche gehört und als UNESCO Weltkulturerbe gelistet ist, befindet sich im südlichen Teil von Delhi, Indiens Hauptstadt, in dem islamisch geprägten Stadtteil Nizamuddin an der Kreuzung Lodi Road und Mathura Road.'}
]



pois.forEach(function (poi){
    document.getElementById('row').insertAdjacentHTML("beforeend", `
    <div class="column ${poi.ort}" style="min-height:700px">										
<div class="content">										
<img src="${poi.foto}" alt="${poi.alt}" style="width:100%; height:300px;object-fit:cover">										
<div class="w3-container w3-white">										
<p><b><a href="${poi.link}" target="_blank">${poi.place}</a></b></p>										
<p>${poi.text}</p>										
</div>										
</div>										
</div>`)
})



filterSelection("all")
function filterSelection(c) {
  var x, i;
  x = document.getElementsByClassName("column");
  if (c == "all") c = "";
  for (i = 0; i < x.length; i++) {
    w3RemoveClass(x[i], "show");
    if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
  }
}

function w3AddClass(element, name) {
  var i, arr1, arr2;
  arr1 = element.className.split(" ");
  arr2 = name.split(" ");
  for (i = 0; i < arr2.length; i++) {
    if (arr1.indexOf(arr2[i]) == -1) {element.className += " " + arr2[i];}
  }
}

function w3RemoveClass(element, name) {
  var i, arr1, arr2;
  arr1 = element.className.split(" ");
  arr2 = name.split(" ");
  for (i = 0; i < arr2.length; i++) {
    while (arr1.indexOf(arr2[i]) > -1) {
      arr1.splice(arr1.indexOf(arr2[i]), 1);     
    }
  }
  element.className = arr1.join(" ");
}


// Add active class to the current button (highlight it)
var btnContainer = document.getElementById("myBtnContainer");
var btns = btnContainer.getElementsByClassName("btn");
for (var i = 0; i < btns.length; i++) {
  btns[i].addEventListener("click", function(){
    var current = document.getElementsByClassName("active");
    current[0].className = current[0].className.replace(" active", "");
    this.className += " active";
  });
}